### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by kans** [coreos/grafiti#48]
grafiti --dry-run delete --all-deps -f df.json
INFO[0000] Using config file:/Users/kans/.grafiti.toml

```goroutine 1 [running]:
github.com/coreos/grafiti/graph.traverseDependencyGraph(0x164b086, 0x22, 0xc4202b2e10)
	/Users/kans/go/src/github.com/coreos/grafiti/graph/graph.go:93 +0x46c
github.com/coreos/grafiti/graph.FillDependencyGraph(0xc4202b2e10)
	/Users/kans/go/src/github.com/coreos/grafiti/graph/graph.go:46 +0x137
main.bucketARNs(0xc420094180, 0x5, 0x8, 0xc420078020)
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/delete.go:398 +0x4da
main.deleteARNs(0xc420094180, 0x5, 0x8, 0x0, 0x0)
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/delete.go:411 +0x5a
main.deleteFromTags(0x1945ac0, 0xc420076b40, 0x1000, 0xc42018a000)
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/delete.go:147 +0x342
main.deleteFromFile(0x7fff5fbff76f, 0x7, 0x1, 0xc420096090)
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/delete.go:108 +0xb8
main.runDeleteCommand(0x19787a0, 0xc420090f00, 0x0, 0x4, 0x0, 0x0)
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/delete.go:94 +0x85
github.com/coreos/grafiti/vendor/github.com/spf13/cobra.(*Command).execute(0x19787a0, 0xc420090d00, 0x4, 0x4, 0x19787a0, 0xc420090d00)
	/Users/kans/go/src/github.com/coreos/grafiti/vendor/github.com/spf13/cobra/command.go:644 +0x3f2
github.com/coreos/grafiti/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1978c20, 0x1, 0x0, 0x0)
	/Users/kans/go/src/github.com/coreos/grafiti/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/coreos/grafiti/vendor/github.com/spf13/cobra.(*Command).Execute(0x1978c20, 0xc420000340, 0xc420000340)
	/Users/kans/go/src/github.com/coreos/grafiti/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/Users/kans/go/src/github.com/coreos/grafiti/cmd/grafiti/main.go:67 +0x2d
```

config:
```toml
[grafiti]
resourceTypes = ["AWS::EC2::Instance"]
hours = -8
az = "us-east-1"
includeEvent = false
tagPatterns = [
  "{CreatedBy: .userIdentity.arn}",
#  "{CreatedAt: .eventTime}",
#  "{TaggedAt: now|todate}",
   "{TaggedAt: now|strftime(\"%Y-%m-%d\")}",
   "{ExpiresAt: (now+(60*60*24*14))|strftime(\"%Y-%m-%d\")}" # Expire in 2 weeks
]
filterPatterns = [
#  ".TaggingMetadata.ResourceType == \"AWS::EC2::Instance\"",
#  ".TaggingMetadata.ResourceType != \"AWS::CloudTrail::Trail\"",
]
```

df.json
```json
{
        "TagFilters": [
                {
                        "Key": "Name",
                        "Values": ["aws-pr-688-31012345678901234-worker"]
                }
        ]
}
```
